# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :'server' => {
        :box_name => "centos/8",
        :ip_addr => '192.168.11.100',
        :cpus => '4',
        :ram => '4096',

  },
  :'client' => {
    :box_name => "centos/8",
    :ip_addr => '192.168.11.101',
    :cpus => '1',
    :ram => '512',

    },



}

Vagrant.configure("2") do |config|
  #config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    #ansible.playbook = "ansible/pg.yaml"
    #ansible.become = "true"
  #end

 MACHINES.each do |boxname, boxconfig|


      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", boxconfig[:ram], "--cpus", boxconfig[:cpus]]
      end

 	   box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
         	  SHELL

      end
  end
end

