---
- name: CONSUL
  hosts: dcs
  become: yes
  roles:
     - consul

- name: PATRONI
  hosts: dbs
  become: yes
  roles:
   - patroni

- name: HAPROXY
  hosts: prx
  become: yes
  roles:
   - haproxy
  tags:
    - haproxy