# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :client => {
        :box_name => "centos/7",
          :net => [
                  {ip: '10.0.0.1',adapter: 2, netmask: "255.255.255.248",virtualbox__intnet: "NET1"},            
                ]
              },
    
  :bridge => {
        :box_name => "centos/7",
        :net => [
                   { adapter: 2, auto_config: false,virtualbox__intnet: "NET1"},
                   { adapter: 3, auto_config: false,virtualbox__intnet: "NET2"},
                   
                ]
              },
  :server => {
        :box_name => "centos/7",
        :net => [
                  {ip: '10.0.0.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "NET2"},
                  
                ]
              }
  }

Vagrant.configure("2") do |config|
  config.vm.provision "ansible" do |ansible|
   #ansible.verbose = "vvv"
     ansible.playbook = "provisioning/br_vpn.yml"
     ansible.become = "true"
   end

  MACHINES.each do |boxname, boxconfig|


    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end
      
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
     end
    config.vm.define "bridge" do |bridge|
    bridge.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm",:id,"--nicpromisc2","allow-all"]
      v.customize ["modifyvm",:id,"--nicpromisc3","allow-all"]
    end
    end
    end
 end
