# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :R1 => {
        :box_name => "centos/7",
          :net => [
                  {ip: '10.10.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "vlan1"},            
                  {ip: '10.0.0.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "vlan2"},
                   ]
  },
  :R2 => {
        :box_name => "centos/7",
          :net => [
                  {ip: '10.20.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "vlan3"},            
                  {ip: '10.0.0.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "vlan2"},
                   ]
  },
  :R3 => {
        :box_name => "centos/7",
          :net => [
                  {ip: '10.10.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "vlan1"},            
                  {ip: '10.20.0.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "vlan3"},
                   ]
  },  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            SHELL
        
        end

      end

  end
  
  
end
