---
- name: create route file
  file:
    path: /etc/sysconfig/network-scripts/route-eth1
    state: touch 

- name: add route for eth1
  lineinfile:
     path: /etc/sysconfig/network-scripts/route-eth1
     line: 0.0.0.0/0 via 192.168.255.1

- name: Enable routing
  lineinfile:
   path: /etc/sysctl.conf
   regexp: '^net.ipv4.ip_forward = 0'
   line: net.ipv4.ip_forward = 1
   state: present
  notify: reload_sysctl
- name:  echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
- name: echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.255.1

- name: restart network
  systemd:
   name: network
   state: restarted

- name: Install epel-release 
  yum:
   name: epel-release 
   state: present

- name: Vim,tcpdump,nmap
  yum:
   name: "{{item}}"
   state: present
  with_items:
   - vim
   - tcpdump
   - nmap



                                                             

