---
- name: delete default route
  command: ip route delete default

- name: create route file
  file:
    path: /etc/sysconfig/network-scripts/route-eth1
    state: touch 

- name: add route for eth1
  lineinfile:
     path: /etc/sysconfig/network-scripts/route-eth1
     line: 0.0.0.0/0 via 192.168.0.1

- name:  echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no

- name: echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1

- name: restart network2
  command: service network restart

- name: restart systemd
  systemd:
   name: network
   state: restarted

- name: Install epel-release 
  yum:
   name: epel-release 
   state: present

- name: Vim,tcpdump,nmap
  yum:
   name: "{{item}}"
   state: present
  with_items:
   - vim
   - tcpdump
   - nmap
   - nginx

- name: start nginx
  systemd:
   name: nginx
   state: started