filebeat.inputs:                                                                                         
- type: log                                                                                              
  enabled: true                                                                                          
  paths:                                                                                                 
    - /var/log/docker/nginx0/*.log                                                                               
                                                                                                         
filebeat.config.modules:                                                                                 
  path: ${path.config}/modules.d/*.yml                                                                   
  reload.enabled: false                                                                                  
#==================== Elasticsearch template setting ==========================                          
                                                                                                         
setup.template.settings:                                                                                 
  index.number_of_shards: 1                                                                              
  #index.codec: best_compression                                                                         
  #_source.enabled: false                                                                                
                                                                                                         
#----------------------------- Logstash output --------------------------------                          
output.logstash:                                                                                         
  # The Logstash hosts                                                                                   
 hosts: ["192.168.11.102:5044"]                                                                          
                                                               
                                                                                                                                                                                        
                                                                                                   