# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
#
  config.vm.provision "ansible" do |ansible|
  #ansible.verbose = "vvv"
    ansible.playbook = "playbook/ipa.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4 
  end

  config.vm.define "ipa" do |ipa|
    ipa.vm.network "private_network", ip: "192.168.50.10"
    ipa.vm.hostname = "ipa.lab.lan"
  end

  config.vm.define "cl0" do |cl0|
    cl0.vm.network "private_network", ip: "192.168.50.11"
    cl0.vm.hostname = "cl0.lab.lan"
  end

end
