---
# tasks file for roles/consul
- name: install epel-release
  dnf: 
    name: epel-release
    state: present
    
- name: install soft
  dnf:
    name: ['vim','wget','unzip','htop']
    state: present
#inst consul
- include: inst.yml
  tags:
    - install
#conf consul
- include: conf.yml
  tags:
   - conf
