FROM alpine:latest
RUN apk update && apk upgrade && apk add nginx && rm -rf /var/cache/apk/* && \
mkdir /site && touch /site/index.html && echo "hello from my container" >> /site/index.html && \
echo "daemon off;" >> /etc/nginx/nginx.conf && rm -rf /etc/nnginx/conf.d/default.conf && mkdir /run/nginx/ 
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx"]