###
version: '3.7'
services:
    mysql0: 
        image: alexd42/mysql:node
        container_name: mysql0
        hostname: mysql0
        restart: always
        volumes:
            - "/tmp/mysql0_data:/var/lib/mysql"
        
    mysql1: 
        image: alexd42/mysql:node
        container_name: mysql1
        hostname: mysql1
        restart: always
        volumes:
            - "/tmp/mysql1_data:/var/lib/mysql"
        
    mysql2: 
        image: alexd42/mysql:node
        container_name: mysql2
        hostname: mysql2
        restart: always
        volumes:
            - "/tmp/mysql2_data:/var/lib/mysql"
        
    mysql_router: 
        image: alexd42/mysql:router
        container_name: mysql_router
        hostname: mysql_router
        depends_on:
            - mysql0
            - mysql1
            - mysql2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
            - "/tmp/mysql-router_data:/mysql_router"
        ports:
            - 6446:6446
            - 6447:6447
networks:
    mysql_net:
        driver: overlay
    