version: "3.7"
services:
   nginx:
    image: alexd42/hw28_ngnx
    hostname: nginx
    ports:
        - 80:80
        - 8000:8000
        - 9000:9000
        - 4000:4000
    volumes:
        - "./www:/www"
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
        - php-fpm
        - django
        - angular
     
   php-fpm:
    image: alexd42/hw28_php-fpm
    hostname: php-fpm
    volumes:
       - "./www:/www"
   django:
    image: alexd42/hw28_django
    hostname: django
    volumes:
        - "./www:/www"
   angular:
    hostname: angular
    image: alexd42/hw28_angular
    volumes:
        - "./www:/www"
