# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :'doc0' => {
        :box_name => "centos/8",
        :ip_addr => '192.168.11.100',

  },
}

Vagrant.configure("2") do |config|
  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "ansible/doc.yml"
    ansible.become = "true"
  end

 MACHINES.each do |boxname, boxconfig|


      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "4"]
      end

 	   box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
         	  SHELL

      end
  end
end

