# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {adapter: 2,auto_config: false, virtualbox__intnet: "router-net"},
                   {adapter: 3,auto_config: false, virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
          :net => [
                  {adapter: 2, auto_config: false,virtualbox__intnet: "router-net"},            
                  {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                  {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                  {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                  {ip: '192.168.255.5', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {ip: '192.168.255.9', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {adapter: 8, auto_config: false, virtualbox__intnet: "router-net"},
                  
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :office1Router => {
        :box_name => "centos/7",
        :net => [
                  {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-net"},
                  {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "tstsrv-net"},
                  {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mang-net"},
                  {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"}
                ]
  },
  
  :office1Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :office2Router => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
              {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
              {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "tstsrv-net"},
              {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
              
            ]
},

:office2Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
               {adapter: 3, auto_config: false, virtualbox__intnet: true},
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},
:testServer1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "tstsrv-net"},
               {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "tstsrv-net" },
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},
:testServer2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.69', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "tstsrv-net"},
               {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "tstsrv-net"},
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},
:testClient1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.67', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "tstsrv-net"},
               {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "tstsrv-net"},
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},
:testClient2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.68', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "tstsrv-net"},
               {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "tstsrv-net"},
               {adapter: 4, auto_config: false, virtualbox__intnet: true},
            ]
},



}

Vagrant.configure("2") do |config|
  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = "vvv"
     ansible.playbook = "provisioning/netlab.yml"
     ansible.become = "true"
   end

  MACHINES.each do |boxname, boxconfig|


    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
     end
  
   end

 end
