---
# install EPEL-REPO and Update OS
#epel-repo
- name: install epel-repo
  dnf:
   name: epel-release
   state: latest
# update OS
- name: update OS
  dnf:
   name: '*'
   state: latest
# install packages
- name: install packages
  dnf:
   name: [vim,tree,htop,wget,mysql-server,python2-PyMySQL,python3-PyMySQL,telnet]
   state: latest

    