---
- name: start mysql
  systemd:
      name: mysqld
      state: started
      enabled: yes
# Ansible mysql_secure_installation playbook
 
- name: delete anonymous MySQL server user for {{ ansible_hostname }}
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
  ignore_errors: yes
 
- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
  ignore_errors: yes
 
- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  ignore_errors: yes
   
- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes
- name: copy my.cnf
  copy:
    src: mysql/.my.cnf
    dest: /root
  
