---
- name: install EPEL and VIM
  yum:
    name:
      - epel-release
      - vim
    state: present
- name: Install borg
  yum:
   name: borgbackup
   state: present
- name: configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
     - '192.168.11.101  client'
     - '192.168.11.102  server'
