---
  - name: Install nginx 
    hosts: web
    become: true
    vars:
     nginx_listen_port: 8080

    tasks:
    - block: #RH
      - name: Install EPEL Repo 
        yum: 
         name: epel-release
         state: present
        tags:
         - epel-package
         - packages
      - name: Install nginx 
        yum:
         name: nginx
         state: latest
        notify:
          - restart nginx
        tags:
          - nginx-package
          - packages 

      when: ansible_os_family == "RedHat"
    - block: #debian
      - name: Install nginx
        apt:
         name: nginx
         state: latest
        notify:
          - restart nginx
        tags:
          - nginx-package
          - packages
      
      when: ansible_os_family == "Debian"

    - block:
      - name: NGINX | Create nginx.conf
        template:
          src: templates/nginx.conf.j2
          dest: /etc/nginx/nginx.conf
        notify:
          - reload nginx
        tags: nginx configuration 

    handlers:
      - name: restart nginx
        systemd:
         name: nginx
         state: restarted
         enabled: yes
      - name: reload nginx
        systemd:
         name: nginx
         state: reloaded