---
- name: create systemdpatroni unit
  template:
   src: patroni.service.j2
   dest: /etc/systemd/system/patroni.service

- name: Create patroni config folder
  file:
   path: /etc/patroni
   state: directory
   owner: postgres
   group: postgres  

- name: copy patroni.yml
  template:
   src: patroni.yml.j2
   dest: /etc/patroni/patroni.yml

- name: start patroni service
  systemd: 
   name: patroni
   state: started
   enabled: yes