---
- name: Install dnf packages
  dnf:
   name: ['python3','gcc' ,'platform-python-devel', 'python3-psycopg2', 'postgresql-server','postgresql-contrib']
   state: present
- name: Install pip packages
  pip:
    name: [python-consul,patroni]
    state: present
    