---
#SELINUX CONF
- name: set selinux
  seboolean:
    name: "{{item}}"
    state: yes
    persistent: yes
  with_items:
     - httpd_can_sendmail
     - httpd_can_network_connect
     - httpd_execmem
