# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :web0 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        :mem => "1024",
        :core => "1"
	},
  :log0 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
        :mem => "4096",
        :core => "4",
  },
  :doc0 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.103',
        :mem => "1024",
        :core => "1"
	},
  :log1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.104',
        :mem => "2048",
        :core => "2",
      }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", boxconfig[:mem]]
                vb.customize ["modifyvm", :id, "--cpus", boxconfig[:core]]
          end
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	  SHELL
      end
   end
end

