---
# handlers file for roles/conf_os
- name: yum-clean-all
  command: yum clean all
  args:
    warn: no 

- name: yum-makecache-fast
  command: yum makecache fast -y

- name: filebeat-en-ls
  command: filebeat modules enable logstash

- name: stop-auditd
  command: service auditd stop

- name: restart-auditbeat
  command: systemctl restart auditbeat

- name: semanage-rsyslog-ports-tcp
  command: semanage port -m -t syslogd_port_t -p tcp 514

- name: semanage-rsyslog-ports-udp 
  command: semanage port -m -t syslogd_port_t -p udp 514

- name: enabled-rsyslog
  systemd:
    name: rsyslog
    enabled: yes
    state: started

- name: firewall-rsyslog-tcp
  firewalld:
    port: 514/tcp
    permanent: yes
    state: enabled

- name: firewall-rsyslog-udp
  firewalld:
    port: 514/udp
    permanent: yes
    state: enabled