---
- name: Create sudoers.d file
  file:
   path: '/etc/sudoers.d/{{ username }}'
   state: touch
   owner: root
   group: root
   mode: '0440'
- name: add string to file sudoersd/test
  lineinfile:
        dest: /etc/sudoers.d/{{ username}}
        line: '{{ username }}   ALL=(ALL)   NOPASSWD: ALL'
        state: present
        create: yes