---
- name: install epel-repo
  dnf:
   name: epel-release
   state: latest

#- name: update OS
#  dnf:
#   name: '*'
#   state: latest

- name: install packages
  dnf:
   name: [vim,tree,htop,wget,telnet,glibc-langpack-ru,postgresql,postgresql-server,python3-psycopg2,postgresql-contrib]
   state: latest
    