---
- name: Delete default route
  command: ip route delete default

- name: add default route to inetRouter
  shell: ip route add 0.0.0.0/0 via 192.168.255.1 dev eth1

- name: add route to office1
  command: ip route add 192.168.2.0/24 via 192.168.255.6 dev eth5

- name: add route to office2
  command: ip route add 192.168.1.0/24 via 192.168.255.10 dev eth6
 